name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java-version: [23]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build Process Watcher
        uses: cdsap/build-process-watcher@v0.6.0
        with:
          remote_monitoring: 'true'
      - name: Test Android Library
        run: ./gradlew assembleDebug
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_API_KEY }}
